//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödüller.
        /// </summary>
        internal static string AboutAwards {
            get {
                return ResourceManager.GetString("AboutAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla Bilgi.
        /// </summary>
        internal static string AboutMoreInformation {
            get {
                return ResourceManager.GetString("AboutMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigorta Poliçeleri.
        /// </summary>
        internal static string AboutPolicies {
            get {
                return ResourceManager.GetString("AboutPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitelikli Temsilciler.
        /// </summary>
        internal static string AboutSkill {
            get {
                return ResourceManager.GetString("AboutSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paranızı koruyabiliriz..
        /// </summary>
        internal static string AboutSlogan1 {
            get {
                return ResourceManager.GetString("AboutSlogan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün üretimi veya ticareti.
        /// </summary>
        internal static string AboutSlogan2 {
            get {
                return ResourceManager.GetString("AboutSlogan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayat sigortamız esnektir.
        /// </summary>
        internal static string AboutSlogan3 {
            get {
                return ResourceManager.GetString("AboutSlogan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geniş Kapsamlı Güvence Seçenekleri.
        /// </summary>
        internal static string AboutSubTitle {
            get {
                return ResourceManager.GetString("AboutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekip Üyeleri.
        /// </summary>
        internal static string AboutTeam {
            get {
                return ResourceManager.GetString("AboutTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirketimiz Hakkında.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzman Ekip Üyelerimizle Tanışın.
        /// </summary>
        internal static string EmployeeSubtitle {
            get {
                return ResourceManager.GetString("EmployeeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekibimiz.
        /// </summary>
        internal static string EmployeeTitle {
            get {
                return ResourceManager.GetString("EmployeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla Bilgi.
        /// </summary>
        internal static string FeatureLearnMore {
            get {
                return ResourceManager.GetString("FeatureLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigorta Size Daha İyi Bir Gelecek Sunar.
        /// </summary>
        internal static string FeatureSubTitle {
            get {
                return ResourceManager.GetString("FeatureSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özelliklerimiz.
        /// </summary>
        internal static string FeatureTitle {
            get {
                return ResourceManager.GetString("FeatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string FooterAbout {
            get {
                return ResourceManager.GetString("FooterAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string FooterAdress {
            get {
                return ResourceManager.GetString("FooterAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmanlarımıza Telefonla Ulaşın.
        /// </summary>
        internal static string FooterCall {
            get {
                return ResourceManager.GetString("FooterCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string FooterCommun {
            get {
                return ResourceManager.GetString("FooterCommun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dağıtım:.
        /// </summary>
        internal static string FooterDist {
            get {
                return ResourceManager.GetString("FooterDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellikler.
        /// </summary>
        internal static string FooterFeature {
            get {
                return ResourceManager.GetString("FooterFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanışlı Bağlantılar.
        /// </summary>
        internal static string Footerlink {
            get {
                return ResourceManager.GetString("Footerlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bülten.
        /// </summary>
        internal static string FooterNewsletter {
            get {
                return ResourceManager.GetString("FooterNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postanızı girin.
        /// </summary>
        internal static string Footerplaceholdermail {
            get {
                return ResourceManager.GetString("Footerplaceholdermail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır..
        /// </summary>
        internal static string FooterReser {
            get {
                return ResourceManager.GetString("FooterReser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Gönder.
        /// </summary>
        internal static string FooterSendMail {
            get {
                return ResourceManager.GetString("FooterSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetler.
        /// </summary>
        internal static string FooterServices {
            get {
                return ResourceManager.GetString("FooterServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        internal static string FooterSignup {
            get {
                return ResourceManager.GetString("FooterSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Adınız.
        /// </summary>
        internal static string FooterSite {
            get {
                return ResourceManager.GetString("FooterSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS.
        /// </summary>
        internal static string FooterSSS {
            get {
                return ResourceManager.GetString("FooterSSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string FooterTel {
            get {
                return ResourceManager.GetString("FooterTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasarım:.
        /// </summary>
        internal static string FootterDesign {
            get {
                return ResourceManager.GetString("FootterDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükleniyor....
        /// </summary>
        internal static string HeaderLood {
            get {
                return ResourceManager.GetString("HeaderLood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıldız Hayat Sigortası Web Sitesi.
        /// </summary>
        internal static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string Lan1 {
            get {
                return ResourceManager.GetString("Lan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        internal static string Lan2 {
            get {
                return ResourceManager.GetString("Lan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar kelime ile arama.
        /// </summary>
        internal static string ModalKeyWords {
            get {
                return ResourceManager.GetString("ModalKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Sayfa.
        /// </summary>
        internal static string Nav404 {
            get {
                return ResourceManager.GetString("Nav404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string NavAbout {
            get {
                return ResourceManager.GetString("NavAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmanlarımıza ulaşın.
        /// </summary>
        internal static string NavCallExper {
            get {
                return ResourceManager.GetString("NavCallExper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string NavCommun {
            get {
                return ResourceManager.GetString("NavCommun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özelliklerimiz.
        /// </summary>
        internal static string NavFeatures {
            get {
                return ResourceManager.GetString("NavFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Bul.
        /// </summary>
        internal static string NavFind {
            get {
                return ResourceManager.GetString("NavFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücretsiz:.
        /// </summary>
        internal static string NavFree {
            get {
                return ResourceManager.GetString("NavFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Al.
        /// </summary>
        internal static string NavGet {
            get {
                return ResourceManager.GetString("NavGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnaSayfa.
        /// </summary>
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        internal static string NavPages {
            get {
                return ResourceManager.GetString("NavPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetler.
        /// </summary>
        internal static string NavServices {
            get {
                return ResourceManager.GetString("NavServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS.
        /// </summary>
        internal static string NavSSS {
            get {
                return ResourceManager.GetString("NavSSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekibimiz.
        /// </summary>
        internal static string NavTeam {
            get {
                return ResourceManager.GetString("NavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        internal static string NavTest {
            get {
                return ResourceManager.GetString("NavTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birinci Sınıf Haftası&apos;nda neler olur?.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakil başvuru süreci nasıldır?.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden toplum kolejine gitmeliyim?.
        /// </summary>
        internal static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst düzey genel bakışlar için sağlam bir özet sunmak üzere çevik çerçevelerden yararlanın. Kurumsal stratejiye yönelik yinelemeli yaklaşımlar, genel değer önerisini daha da ileriye taşımak için iş birlikçi düşünmeyi teşvik eder. İş yeri çeşitliliği ve güçlendirme yoluyla yıkıcı inovasyonun bütünsel dünya görüşünü organik olarak geliştirin..
        /// </summary>
        internal static string QuestionAns1 {
            get {
                return ResourceManager.GetString("QuestionAns1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst düzey genel bakışlar için sağlam bir özet sunmak üzere çevik çerçevelerden yararlanın. Kurumsal stratejiye yönelik yinelemeli yaklaşımlar, genel değer önerisini daha da ileriye taşımak için iş birlikçi düşünmeyi teşvik eder. İş yeri çeşitliliği ve güçlendirme yoluyla yıkıcı inovasyonun bütünsel dünya görüşünü organik olarak geliştirin..
        /// </summary>
        internal static string QuestionAns2 {
            get {
                return ResourceManager.GetString("QuestionAns2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst düzey genel bakışlar için sağlam bir özet sunmak üzere çevik çerçevelerden yararlanın. Kurumsal stratejiye yönelik yinelemeli yaklaşımlar, genel değer önerisini daha da ileriye taşımak için iş birlikçi düşünmeyi teşvik eder. İş yeri çeşitliliği ve güçlendirme yoluyla yıkıcı inovasyonun bütünsel dünya görüşünü organik olarak geliştirin..
        /// </summary>
        internal static string QuestionAns3 {
            get {
                return ResourceManager.GetString("QuestionAns3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaygın Olarak Sorulan Sorular.
        /// </summary>
        internal static string QuestionSubTitle {
            get {
                return ResourceManager.GetString("QuestionSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bazı Önemli Sık Sorulan Sorular.
        /// </summary>
        internal static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En İyi Hizmetleri Sunuyoruz.
        /// </summary>
        internal static string ServiccesSubTitle {
            get {
                return ResourceManager.GetString("ServiccesSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Hizmetler.
        /// </summary>
        internal static string Servicesother {
            get {
                return ResourceManager.GetString("Servicesother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını Oku.
        /// </summary>
        internal static string ServicesReadmore {
            get {
                return ResourceManager.GetString("ServicesReadmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        internal static string ServicesTitle {
            get {
                return ResourceManager.GetString("ServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla Bilgi.
        /// </summary>
        internal static string SliderLearnMore {
            get {
                return ResourceManager.GetString("SliderLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoyu İzle.
        /// </summary>
        internal static string SliderWatchVideo {
            get {
                return ResourceManager.GetString("SliderWatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YILDIZ SİGORTA&apos;YA HOŞ GELDİNİZ.
        /// </summary>
        internal static string SliderWelcome1 {
            get {
                return ResourceManager.GetString("SliderWelcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayat Sigortası Mutluluk Getirir.
        /// </summary>
        internal static string SliderWelcome2 {
            get {
                return ResourceManager.GetString("SliderWelcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        internal static string TestimTitle {
            get {
                return ResourceManager.GetString("TestimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslarımızın Söyledikleri.
        /// </summary>
        internal static string TetimSubtitle {
            get {
                return ResourceManager.GetString("TetimSubtitle", resourceCulture);
            }
        }
    }
}
