//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompanyProject.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblServices
    {
        public int ServicesId { get; set; }
        public string ServicesCardImageUrl { get; set; }
        public string ServicesCardTitle { get; set; }
        public string ServicesCardDescription { get; set; }
        public string ServicesCardIcon { get; set; }
    }
}
